steps:
  - label: ":go: Build"
    commands:
      - "go build -o hello-app ./hello"
      - "buildkite-agent artifact upload hello-app"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.15"
          propagate-agent-access: true

  - wait

  - label: ":rocket: Run"
    commands:
      - "buildkite-agent artifact download hello-app ."
      - "chmod +x hello-app"
      - "./hello-app Buildkite"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.15"
          propagate-agent-access: true
