steps:
  - input: "Who should we say hello to?"
    fields:
      - text: "Name"
        key: "name"
        required: true

  - wait

  - label: ":go: Build"
    commands:
      - "go build -o hello-app ./hello"
      - "buildkite-agent artifact upload hello-app"
    plugins:
      - docker#v5.13.0:
          image: "golang:1.15"
          mount-buildkite-agent: true

  - wait

  - label: ":rocket: Run"
    commands:
      - "buildkite-agent artifact download hello-app ."
      - "chmod +x hello-app"
      - "./hello-app $$(buildkite-agent meta-data get name)"
    plugins:
      - docker#v5.13.0:
          image: "golang:1.15"
          mount-buildkite-agent: true
